# Generated by Django 5.1.4 on 2025-01-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_downvotes_comment_upvotes_post_downvotes_and_more'),
        ('user_profile', '0002_userprofile_created_at_userprofile_email_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='downvoted_comments', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvoted_comments', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='downvoted_posts', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvoted_posts', to='user_profile.userprofile'),
        ),
    ]
