# Generated by Django 5.1.4 on 2025-03-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_post_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtags',
            new_name='tags',
        ),
    ]
