# Generated by Django 5.1.4 on 2025-03-20 01:02

import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_rename_hashtags_post_tags'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'posts_post_grades') THEN
                    CREATE TABLE posts_post_grades (
                        id SERIAL PRIMARY KEY,
                        post_id UUID REFERENCES posts_post(id) ON DELETE CASCADE,
                        grade_id UUID REFERENCES posts_grade(id) ON DELETE CASCADE,
                        UNIQUE(post_id, grade_id)
                    );
                END IF;
            END $$;
            """,
            reverse_sql="SELECT 1;"
        ),
    ]
