# Generated by Django 5.1.4 on 2025-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_domains', '0002_schooldomain_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldomain',
            name='school_type',
            field=models.CharField(choices=[('ECE', 'Early Childhood Center'), ('K12', 'K-12'), ('HIGHER_ED', 'Higher Education')], default='K12', max_length=10),
        ),
        migrations.AddField(
            model_name='schooldomain',
            name='staff_email_pattern',
            field=models.CharField(blank=True, default='.*@cps.edu', help_text='Regex pattern for staff emails', max_length=255, null=True),
        ),
    ]
