# Generated by Django 4.2.5 on 2024-09-15 00:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=250)),
                ('subject', models.CharField(blank=True, default='', max_length=250)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('overview', models.CharField(blank=True, default='', max_length=200)),
                ('standard', models.TextField(blank=True, default='', max_length=1000)),
                ('subject', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='plans.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('standard', models.TextField(blank=True, default='', max_length=1000)),
                ('objective', models.TextField(blank=True, default='', max_length=1000)),
                ('body', models.TextField(blank=True, default='')),
                ('unit_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='plans.unitplan')),
            ],
        ),
    ]
