# Generated by Django 4.2.5 on 2024-11-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_levels', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='grade_levels.gradelevel'),
        ),
    ]
