# Generated by Django 5.1 on 2024-08-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='it',
            new_name='id',
        ),
    ]
