# Generated by Django 5.1.4 on 2025-02-28 20:57

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_created_at_userprofile_email_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.user_profile_image_path),
        ),
    ]
