# Generated by Django 4.2.5 on 2024-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth0_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
