# Generated by Django 4.2.5 on 2024-11-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_auth0_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
