# Generated by Django 5.1.4 on 2025-03-29 23:16

import groups.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=groups.models.group_profile_image_path)),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_groups', to='user_profile.userprofile')),
                ('members', models.ManyToManyField(related_name='groups', to='user_profile.userprofile')),
                ('pending_members', models.ManyToManyField(blank=True, related_name='pending_groups', to='user_profile.userprofile')),
            ],
        ),
    ]
