# Generated by Django 5.1.4 on 2025-04-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
