# Generated by Django 4.2.5 on 2023-09-21 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_resource_unitplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='created',
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.URLField(default='DEFAULT VALUE'),
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('standard', models.TextField(max_length=1000)),
                ('objective', models.TextField(max_length=1000)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.lessonoutline')),
            ],
        ),
    ]
