# Generated by Django 4.2.5 on 2024-09-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_lessonplan_user_id_alter_material_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
