# Generated by Django 4.2.5 on 2023-09-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_remove_lessonplan_outline_remove_unitplan_resource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonplan',
            old_name='unitplan',
            new_name='unit_plan',
        ),
        migrations.RemoveField(
            model_name='material',
            name='resource',
        ),
        migrations.AddField(
            model_name='material',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.lessonplan'),
        ),
    ]
