# Generated by Django 4.2.5 on 2023-09-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_rename_unitplan_lessonplan_unit_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonoutline',
            old_name='lessonplan',
            new_name='lesson_plan',
        ),
    ]
