# Generated by Django 4.2.5 on 2023-09-21 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_lessonoutline_remove_plan_created_resource_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='outline',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='plan.lessonoutline'),
        ),
    ]
