# Generated by Django 4.2.5 on 2023-09-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_lessonplan_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='outline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.lessonoutline'),
        ),
    ]
