# Generated by Django 4.2.5 on 2023-11-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_alter_lessonoutline_lesson_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='plan.plan'),
        ),
    ]
