# Generated by Django 4.2.5 on 2023-12-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_alter_unitplan_overview_alter_unitplan_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitplan',
            name='overview',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='standard',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='unitplan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
