# Generated by Django 4.2.5 on 2023-12-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_rename_resource_resource_unit_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='Subject',
        ),
    ]
