# Generated by Django 4.2.5 on 2024-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_rename_plan_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
