# Generated by Django 4.2.5 on 2024-06-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_lessonplan_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonOutline',
        ),
    ]
