# Generated by Django 5.1.4 on 2024-12-27 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedules.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedules.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDayClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schoolclass')),
                ('school_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schoolday')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('school_day', 'order'), ('school_day', 'school_class')},
            },
        ),
    ]
