# Generated by Django 4.2.5 on 2024-10-13 22:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedules.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDayClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schoolclass')),
                ('school_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schoolday')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('school_day', 'school_class'), ('school_day', 'order')},
            },
        ),
    ]
