# Generated by Django 5.1.4 on 2024-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sub_url_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='url_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
