# Generated by Django 5.1.4 on 2025-01-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('upvote', 'Upvote'), ('upvote_post', 'Upvote_post'), ('upvote_comment', 'Upvote_comment')], max_length=36),
        ),
    ]
