# Generated by Django 5.1.4 on 2025-04-07 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_admins'),
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('upvote', 'Upvote'), ('upvote_post', 'Upvote_post'), ('upvote_comment', 'Upvote_comment'), ('group_invite_accepted', 'Group_invite')], max_length=36),
        ),
    ]
