# Generated by Django 5.1.4 on 2024-12-27 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_levels', models.ManyToManyField(related_name='standard_grade_levels', to='grade_levels.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_levels', models.ManyToManyField(related_name='domains', to='standards.gradelevels')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('full_code', models.CharField(max_length=200)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='standards.domain')),
                ('grade_levels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard', to='standards.gradelevels')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('issuing_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='standards.issuingauthority')),
            ],
        ),
        migrations.AddField(
            model_name='gradelevels',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='standards.subject'),
        ),
    ]
