# Generated by Django 4.2.5 on 2024-11-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_levels', '0001_initial'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevels',
            name='grade_levels',
            field=models.ManyToManyField(related_name='standard_grade_levels', to='grade_levels.gradelevel'),
        ),
    ]
