# Generated by Django 4.2.5 on 2024-11-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_alter_gradelevels_grade_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='grade_levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard', to='standards.gradelevels'),
        ),
    ]
