# Generated by Django 4.2.5 on 2024-11-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_standard_grade_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='grade_levels',
        ),
        migrations.AddField(
            model_name='domain',
            name='grade_levels',
            field=models.ManyToManyField(related_name='domains', to='standards.gradelevels'),
        ),
    ]
